# Generated by Django 5.2.14 on 2026-07-01 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenhouse',
            name='size_sq_m',
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 1, 18, 57, 41, 408560, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='greenhouse_code',
            field=models.CharField(help_text='Example: GH001', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='greenhouse_type',
            field=models.CharField(choices=[('Tunnel', 'Tunnel'), ('Gothic', 'Gothic'), ('Multi-Span', 'Multi-Span'), ('Shade Net', 'Shade Net'), ('Other', 'Other')], default='Tunnel', max_length=20),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='length_m',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='width_m',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
