# Generated by Django 5.2.14 on 2026-07-01 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0002_remove_greenhouse_size_sq_m_greenhouse_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
