# Generated by Django 5.2.14 on 2026-07-01 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0003_alter_greenhouse_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_code', models.CharField(max_length=20)),
                ('bed_name', models.CharField(max_length=100)),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of plants this bed can hold.')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='sqlApp.greenhouse')),
            ],
            options={
                'ordering': ['greenhouse', 'bed_code'],
                'unique_together': {('greenhouse', 'bed_code')},
            },
        ),
    ]
