# Generated by Django 5.2.14 on 2026-07-02 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0004_bed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['crop_name']},
        ),
        migrations.RemoveField(
            model_name='crop',
            name='crop_type',
        ),
        migrations.AddField(
            model_name='crop',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety_name', models.CharField(max_length=100)),
                ('expected_yield_per_plant', models.DecimalField(decimal_places=2, help_text='Expected yield (kg) per plant.', max_digits=5)),
                ('maturity_days', models.PositiveIntegerField(help_text='Days from transplant to first harvest.')),
                ('plant_spacing_cm', models.PositiveIntegerField()),
                ('row_spacing_cm', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='sqlApp.crop')),
            ],
            options={
                'ordering': ['crop', 'variety_name'],
                'unique_together': {('crop', 'variety_name')},
            },
        ),
    ]
