# Generated by Django 5.2.14 on 2026-07-03 11:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0005_alter_crop_options_remove_crop_crop_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_code', models.CharField(max_length=10, unique=True)),
                ('grade_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_marketable', models.BooleanField(default=True, help_text='Can this grade be sold?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['grade_code'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['maintenance_name'],
            },
        ),
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Litre'), ('ml', 'Millilitre'), ('pcs', 'Pieces'), ('bags', 'Bags'), ('packs', 'Packs'), ('bottles', 'Bottles')], max_length=20)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(help_text='Example: 2026 Dry Season', max_length=100, unique=True)),
                ('season_type', models.CharField(choices=[('Rainy', 'Rainy'), ('Dry', 'Dry'), ('Special', 'Special')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['bay', 'bed_code']},
        ),
        migrations.AlterModelOptions(
            name='harvest',
            options={'ordering': ['-harvest_date']},
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='greenhouse',
        ),
        migrations.AddField(
            model_name='harvest',
            name='average_fruit_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='crates',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='harvest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='harvest',
            name='harvested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='harvest_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvest',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_code', models.CharField(max_length=20)),
                ('bay_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='sqlApp.greenhouse')),
            ],
            options={
                'ordering': ['greenhouse', 'bay_code'],
                'unique_together': {('greenhouse', 'bay_code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bed',
            name='bay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='sqlApp.bay'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('bay', 'bed_code')},
        ),
        migrations.AddField(
            model_name='harvest',
            name='harvest_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='sqlApp.harvestgrade'),
        ),
        migrations.CreateModel(
            name='NurseryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=30, unique=True)),
                ('sowing_date', models.DateField()),
                ('expected_germination_date', models.DateField()),
                ('expected_transplant_date', models.DateField()),
                ('seeds_sown', models.PositiveIntegerField()),
                ('trays_used', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Seeded', 'Seeded'), ('Germinating', 'Germinating'), ('Ready', 'Ready for Transplant'), ('Completed', 'Completed')], default='Seeded', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursery_batches', to='sqlApp.cropvariety')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursery_batches', to='sqlApp.season')),
            ],
            options={
                'ordering': ['-sowing_date'],
            },
        ),
        migrations.CreateModel(
            name='NurseryInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('germinated_seedlings', models.PositiveIntegerField()),
                ('healthy_seedlings', models.PositiveIntegerField()),
                ('weak_seedlings', models.PositiveIntegerField(default=0)),
                ('dead_seedlings', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nursery_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='sqlApp.nurserybatch')),
            ],
            options={
                'ordering': ['inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='PackingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_date', models.DateField()),
                ('package_type', models.CharField(max_length=100)),
                ('number_of_packages', models.PositiveIntegerField()),
                ('weight_per_package', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Completed', 'Completed')], default='Open', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_batches', to='sqlApp.harvest')),
                ('packed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-packing_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Issue', 'Issue'), ('Return', 'Return'), ('Adjustment', 'Adjustment'), ('Transfer', 'Transfer')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Purchase Order, Production Cycle, Invoice, etc.', max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='sqlApp.product')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='sqlApp.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.CharField(help_text='Example: PC-2026-001', max_length=30, unique=True)),
                ('nursery_date', models.DateField()),
                ('expected_transplant_date', models.DateField()),
                ('actual_transplant_date', models.DateField(blank=True, null=True)),
                ('expected_first_harvest', models.DateField(blank=True, null=True)),
                ('expected_last_harvest', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Nursery', 'Nursery'), ('Ready for Transplant', 'Ready for Transplant'), ('Growing', 'Growing'), ('Harvesting', 'Harvesting'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Planning', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_cycles', to='sqlApp.cropvariety')),
                ('nursery_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_cycles', to='sqlApp.nurserybatch')),
                ('responsible_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_cycles', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_cycles', to='sqlApp.season')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionCycleBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transplanted_seedlings', models.PositiveIntegerField()),
                ('transplant_date', models.DateField()),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Transplanted', 'Transplanted'), ('Growing', 'Growing'), ('Harvesting', 'Harvesting'), ('Completed', 'Completed')], default='Planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_cycles', to='sqlApp.bed')),
                ('production_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_beds', to='sqlApp.productioncycle')),
            ],
            options={
                'ordering': ['production_cycle', 'bed'],
                'unique_together': {('production_cycle', 'bed')},
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Optional quantity applied.', max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, help_text='Examples: L, kg, g, ml, hours', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='sqlApp.maintenancetype')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_activities', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Product used during this activity.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='sqlApp.product')),
                ('production_cycle_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='sqlApp.productioncyclebed')),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.AddField(
            model_name='harvest',
            name='production_cycle_bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='sqlApp.productioncyclebed'),
        ),
        migrations.CreateModel(
            name='ProductionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_events', to=settings.AUTH_USER_MODEL)),
                ('production_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sqlApp.productioncycle')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_variety', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_sop', to='sqlApp.cropvariety')),
            ],
            options={
                'ordering': ['crop_variety'],
            },
        ),
        migrations.CreateModel(
            name='Scouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scouting_date', models.DateField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('affected_plants', models.PositiveIntegerField(default=0)),
                ('recommendation', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sqlApp.disease')),
                ('observed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sqlApp.pest')),
                ('production_cycle_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_records', to='sqlApp.productioncyclebed')),
            ],
            options={
                'ordering': ['-scouting_date'],
            },
        ),
        migrations.CreateModel(
            name='SOPActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=150)),
                ('day_after_sowing', models.PositiveIntegerField()),
                ('frequency', models.CharField(choices=[('Once', 'Once'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Once', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('maintenance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sqlApp.maintenancetype')),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sqlApp.productionsop')),
            ],
            options={
                'ordering': ['day_after_sowing'],
            },
        ),
        migrations.CreateModel(
            name='ActivityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('Product', 'Product'), ('Labour', 'Labour'), ('Equipment', 'Equipment')], max_length=20)),
                ('resource_name', models.CharField(blank=True, help_text='Used for labour or equipment.', max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=30)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_resources', to='sqlApp.product')),
                ('sop_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='sqlApp.sopactivity')),
            ],
            options={
                'ordering': ['resource_type'],
            },
        ),
        migrations.RemoveField(
            model_name='bed',
            name='greenhouse',
        ),
    ]
