# Generated by Django 5.2.14 on 2026-07-03 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0006_disease_harvestgrade_maintenancetype_pest_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncycle',
            name='greenhouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_cycles', to='sqlApp.greenhouse'),
        ),
    ]
