# Generated by Django 5.2.14 on 2026-07-04 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0007_productioncycle_greenhouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='production_cycle_bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='sqlApp.productioncyclebed'),
        ),
        migrations.CreateModel(
            name='ProductionCycleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seedlings', models.PositiveIntegerField(default=0)),
                ('total_harvest_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_crates', models.PositiveIntegerField(default=0)),
                ('marketable_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rejected_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_yield_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_yield_per_plant', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('actual_yield_per_bed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='sqlApp.productioncycle')),
            ],
        ),
    ]
