# Generated by Django 5.2.14 on 2026-07-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0008_alter_harvest_production_cycle_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetype',
            name='affects_crop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='deduct_inventory',
            field=models.BooleanField(default=False, help_text='Should this operation reduce inventory?'),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='requires_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='requires_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='requires_quantity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='requires_remarks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='requires_unit',
            field=models.BooleanField(default=False),
        ),
    ]
