# Generated by Django 5.2.14 on 2026-07-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0009_maintenancetype_affects_crop_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenanceType',
            new_name='OperationType',
        ),
    ]
