# Generated by Django 5.2.14 on 2026-07-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0010_rename_maintenancetype_operationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current quantity available in inventory.', max_digits=10),
        ),
    ]
