# Generated by Django 5.2.14 on 2026-07-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0012_supplier_stockreceipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationlog',
            old_name='cost',
            new_name='labour_cost',
        ),
        migrations.AddField(
            model_name='operationlog',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
