# Generated by Django 5.2.14 on 2026-07-10 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0013_rename_cost_operationlog_labour_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationlog',
            options={'ordering': ['-activity_date', '-id']},
        ),
        migrations.RemoveField(
            model_name='operationlog',
            name='production_cycle_bed',
        ),
        migrations.AddField(
            model_name='operationlog',
            name='apply_to',
            field=models.CharField(choices=[('BEDS', 'Selected Beds'), ('BAY', 'Entire Bay'), ('GREENHOUSE', 'Entire Greenhouse')], default='BEDS', max_length=20),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='bay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='sqlApp.bay'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='beds',
            field=models.ManyToManyField(blank=True, related_name='operations', to='sqlApp.productioncyclebed'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='operation_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='production_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='sqlApp.productioncycle'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='sqlApp.operationtype'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='sqlApp.product'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
