# Generated by Django 5.2.14 on 2026-07-10 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0014_alter_operationlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='operation_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='production_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='sqlApp.productioncycle'),
        ),
    ]
