# Generated by Django 5.2.14 on 2026-07-11 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0015_alter_operationlog_operation_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationlog',
            name='beds',
        ),
        migrations.AddField(
            model_name='operationlog',
            name='greenhouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sqlApp.greenhouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationlog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='bay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sqlApp.bay'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sqlApp.operationtype'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sqlApp.product'),
        ),
        migrations.CreateModel(
            name='OperationBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='sqlApp.bed')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_beds', to='sqlApp.operationlog')),
            ],
            options={
                'unique_together': {('operation', 'bed')},
            },
        ),
    ]
