# Generated by Django 5.2.16 on 2026-07-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0016_remove_operationlog_beds_operationlog_greenhouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bay',
            name='bay_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='nurserybatch',
            name='batch_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
