# Generated by Django 5.2.16 on 2026-07-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0017_alter_bay_bay_code_alter_bed_bed_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='greenhouse_code',
            field=models.CharField(blank=True, help_text='Example: GH001', max_length=20, null=True, unique=True),
        ),
    ]
