# Generated by Django 5.2.16 on 2026-07-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlApp', '0018_alter_greenhouse_greenhouse_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bay',
            name='bay_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
